font_size 13.0
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

scrollback_lines 10000
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes

hide_window_decorations yes

allow_hyperlinks yes

map f11 toggle_fullscreen
map kitty_mod+enter no-op
map cmd+enter       no-op

shell_integration enabled

map ctrl+shift+с copy_to_clipboard
map ctrl+shift+м paste_from_clipboard

include current-theme.conf

enable_audio_bell no
