exec gnome-keyring-daemon --start --components=secrets
exec autotiling-rs
exec nwg-look -a
exec swaync -c ~/.config/swaync/config.json
exec swaybg --image ~/Pictures/Wallpapers/wallpaper1.jpg --mode fill

# Clipboard managers
exec wl-paste --type text --watch cliphist -max-items 50 store
exec wl-paste --type image --watch cliphist -max-items 50 store
exec wl-clip-persist --clipboard regular --write-timeout 1000 --selection-size-limit 2097152

# Cursor
seat seat0 xcursor_theme BreezeX-RosePine-Linux 24

# Xdg desktop (ebanaya hueta zaebala)
exec_always {
    systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
    dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
    systemctl --user restart xdg-desktop-portal
}

# Polkit agent
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
