font pango:JetBrainsMono Nerd Font 10, FontAwesome 10
bar {
    position top
    status_command i3status-rs ~/.config/i3status-rust/config.toml
    swaybar_command swaybar
    colors {
        background #000000
        statusline #ffffff
        separator  #666666
        focused_workspace  #35689e #35689e #ffffff
        active_workspace   #000000 #ffffff #000000
        inactive_workspace #000000 #000000 #ffffff
        urgent_workspace   #000000 #000000 #ffffff
    }
    mode dock
}
